import {
  AnglesDownIcon,
  AnglesLeftIcon,
  AnglesRightIcon,
  AnglesUpIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  BarsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleExclamationIcon,
  CircleInfoIcon,
  CircleMinusIcon,
  CircleNotchIcon,
  CirclePlusIcon,
  CloseCircleIcon,
  CloseIcon,
  CopyIcon,
  DoubleArrowHorizontalIcon,
  DoubleArrowVerticalIcon,
  DownloadIcon,
  EditIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  FastForwardIcon,
  BellIcon,
  BellOffIcon,
  ChatIcon,
  ChatDotsIcon,
  FlagIcon,
  FileIcon,
  FilterIcon,
  FolderIcon,
  GiftIcon,
  AlarmClockIcon,
  HomeIcon,
  KeyIcon,
  GlobeIcon,
  LinkIcon,
  LockIcon,
  MailIcon,
  MailOpenIcon,
  LifeBuoyIcon,
  MinusIcon,
  MoonIcon,
  CreditCardIcon,
  LocationPinIcon,
  ClockIcon,
  PauseIcon,
  PlayIcon,
  PhoneIcon,
  PhoneOffIcon,
  PlusIcon,
  PrintIcon,
  ShoppingCartIcon,
  RefreshIcon,
  RotateLeftIcon,
  RotateRightIcon,
  RewindIcon,
  SaveIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShieldLockIcon,
  StarIcon,
  SunIcon,
  StopIcon,
  StopwatchIcon,
  ToggleOffIcon,
  ToggleOnIcon,
  TrashIcon,
  UnlockIcon,
  UploadIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  HourglassHalfIcon,
  HourglassIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  WarningDiamondIcon,
  WarningTriangleIcon,
} from "./components.js";

// Icon registry - maps icon names to their components
export const iconPaths = {
  "angles-left": <AnglesLeftIcon />,
  "angles-right": <AnglesRightIcon />,
  "angles-up": <AnglesUpIcon />,
  "angles-down": <AnglesDownIcon />,
  "arrow-right": <ArrowRightIcon />,
  "arrow-left": <ArrowLeftIcon />,
  "arrow-up": <ArrowUpIcon />,
  "arrow-down": <ArrowDownIcon />,
  "arrow-up-right": <ArrowUpRightIcon />,
  "arrow-up-left": <ArrowUpLeftIcon />,
  "arrow-down-right": <ArrowDownRightIcon />,
  "arrow-down-left": <ArrowDownLeftIcon />,
  bars: <BarsIcon />,
  "caret-left": <CaretLeftIcon />,
  "caret-right": <CaretRightIcon />,
  "caret-up": <CaretUpIcon />,
  "caret-down": <CaretDownIcon />,
  "chevron-left": <ChevronLeftIcon />,
  "chevron-right": <ChevronRightIcon />,
  "chevron-up": <ChevronUpIcon />,
  "chevron-down": <ChevronDownIcon />,
  "circle-check": <CircleCheckIcon />,
  "circle-exclamation": <CircleExclamationIcon />,
  "circle-info": <CircleInfoIcon />,
  "circle-minus": <CircleMinusIcon />,
  "circle-notch": <CircleNotchIcon />,
  "circle-plus": <CirclePlusIcon />,
  "circle-close": <CloseCircleIcon />,
  close: <CloseIcon />,
  copy: <CopyIcon />,
  "double-arrow-horizontal": <DoubleArrowHorizontalIcon />,
  "double-arrow-vertical": <DoubleArrowVerticalIcon />,
  download: <DownloadIcon />,
  edit: <EditIcon />,
  "ellipsis-vertical": <EllipsisVerticalIcon />,
  ellipsis: <EllipsisIcon />,
  "external-link": <ExternalLinkIcon />,
  "fast-forward": <FastForwardIcon />,
  bell: <BellIcon />,
  "bell-off": <BellOffIcon />,
  chat: <ChatIcon />,
  "chat-dots": <ChatDotsIcon />,
  flag: <FlagIcon />,
  gift: <GiftIcon />,
  "alarm-clock": <AlarmClockIcon />,
  file: <FileIcon />,
  filter: <FilterIcon />,
  folder: <FolderIcon />,
  home: <HomeIcon />,
  key: <KeyIcon />,
  globe: <GlobeIcon />,
  link: <LinkIcon />,
  lock: <LockIcon />,
  mail: <MailIcon />,
  "mail-open": <MailOpenIcon />,
  "life-buoy": <LifeBuoyIcon />,
  "credit-card": <CreditCardIcon />,
  minus: <MinusIcon />,
  moon: <MoonIcon />,
  clock: <ClockIcon />,
  "location-pin": <LocationPinIcon />,
  pause: <PauseIcon />,
  play: <PlayIcon />,
  phone: <PhoneIcon />,
  "phone-off": <PhoneOffIcon />,
  plus: <PlusIcon />,
  print: <PrintIcon />,
  refresh: <RefreshIcon />,
  "shopping-cart": <ShoppingCartIcon />,
  "rotate-left": <RotateLeftIcon />,
  "rotate-right": <RotateRightIcon />,
  rewind: <RewindIcon />,
  save: <SaveIcon />,
  search: <SearchIcon />,
  settings: <SettingsIcon />,
  share: <ShareIcon />,
  "shield-check": <ShieldCheckIcon />,
  "shield-exclamation": <ShieldExclamationIcon />,
  "shield-lock": <ShieldLockIcon />,
  star: <StarIcon />,
  sun: <SunIcon />,
  stop: <StopIcon />,
  stopwatch: <StopwatchIcon />,
  "toggle-off": <ToggleOffIcon />,
  "toggle-on": <ToggleOnIcon />,
  trash: <TrashIcon />,
  unlock: <UnlockIcon />,
  upload: <UploadIcon />,
  user: <UserIcon />,
  users: <UsersIcon />,
  "user-minus": <UserMinusIcon />,
  "user-plus": <UserPlusIcon />,
  hourglass: <HourglassIcon />,
  "hourglass-half": <HourglassHalfIcon />,
  "volume-off": <VolumeOffIcon />,
  "volume-up": <VolumeUpIcon />,
  "warning-diamond": <WarningDiamondIcon />,
  "warning-triangle": <WarningTriangleIcon />,
} as const;

export type IconName = keyof typeof iconPaths;
