import {
  AnglesDownIcon,
  AnglesLeftIcon,
  AnglesRightIcon,
  AnglesUpIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  BarsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleExclamationIcon,
  CircleInfoIcon,
  InfoIcon,
  CircleIcon,
  CircleMinusIcon,
  CircleNotchIcon,
  CirclePlusIcon,
  CloseCircleIcon,
  CloseIcon,
  CopyIcon,
  InboxIcon,
  SendIcon,
  ReplyIcon,
  ForwardIcon,
  HashtagIcon,
  ClipboardIcon,
  ClipboardListIcon,
  ClipboardCheckIcon,
  ClipboardPlusIcon,
  CutIcon,
  PasteIcon,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  AlignLeftIcon,
  AlignCenterIcon,
  AlignRightIcon,
  AlignJustifyIcon,
  UnlinkIcon,
  ShoppingBagIcon,
  WalletIcon,
  WalletCardIcon,
  ReceiptIcon,
  EyeIcon,
  EyeOffIcon,
  DoubleArrowHorizontalIcon,
  DoubleArrowVerticalIcon,
  DownloadIcon,
  EditIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  CalendarIcon,
  FastForwardIcon,
  BellIcon,
  BellOffIcon,
  ChatIcon,
  ChatDotsIcon,
  FlagIcon,
  FileIcon,
  FileTextIcon,
  FileImageIcon,
  FileVideoIcon,
  FileCodeIcon,
  FilterIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FolderMinusIcon,
  MapPinIcon,
  PinIcon,
  MapIcon,
  RouteIcon,
  CompassNorthIcon,
  CompassIcon,
  BookmarkIcon,
  TagIcon,
  PaperclipIcon,
  GiftIcon,
  AlarmClockIcon,
  HomeIcon,
  KeyIcon,
  GlobeIcon,
  LinkIcon,
  LockIcon,
  MailIcon,
  MailOpenIcon,
  LifeBuoyIcon,
  MinusIcon,
  MoonIcon,
  CircleQuestionIcon,
  QuestionIcon,
  CreditCardIcon,
  CouponIcon,
  CubeIcon,
  TruckIcon,
  LocationPinIcon,
  ClockIcon,
  PauseIcon,
  PlayIcon,
  PhoneIcon,
  PhoneOffIcon,
  CameraIcon,
  VideoIcon,
  MicIcon,
  MicOffIcon,
  HeadphonesIcon,
  MonitorIcon,
  LaptopIcon,
  MobileIcon,
  ShuffleIcon,
  RepeatIcon,
  RepeatOneIcon,
  SkipNextIcon,
  SkipPreviousIcon,
  RecordIcon,
  VolumeDownIcon,
  PlusIcon,
  PrintIcon,
  ShoppingCartIcon,
  CloudIcon,
  CloudSunIcon,
  CloudRainIcon,
  CloudsIcon,
  WindIcon,
  CloudSnowIcon,
  CloudStormIcon,
  UploadCloudIcon,
  BatteryEmptyIcon,
  BatteryHalfIcon,
  BatteryFullIcon,
  WifiIcon,
  SignalIcon,
  DownloadCloudIcon,
  UmbrellaIcon,
  ThermometerIcon,
  ThermometerPlusIcon,
  ThermometerMinusIcon,
  GridIcon,
  ListIcon,
  RefreshIcon,
  RectangleIcon,
  SquareIcon,
  RotateLeftIcon,
  RotateRightIcon,
  RewindIcon,
  SaveIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShieldLockIcon,
  StarIcon,
  SunIcon,
  StopIcon,
  StopwatchIcon,
  ZoomInIcon,
  ZoomOutIcon,
  ToggleOffIcon,
  ToggleOnIcon,
  TrashIcon,
  UnlockIcon,
  UploadIcon,
  HeartIcon,
  CheckIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  HourglassHalfIcon,
  HourglassFullIcon,
  HourglassIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  WarningDiamondIcon,
  WarningTriangleIcon,
  TriangleIcon,
  CalendarPlusIcon,
  CalendarMinusIcon,
  CalendarCheckIcon,
  CalendarRangeIcon,
  LogInIcon,
  LogOutIcon,
  UserCheckIcon,
  UserEditIcon,
  UserSettingsIcon,
  ChartLineIcon,
  ChartBarIcon,
  PieChartIcon,
  SlidersIcon,
  TerminalIcon,
  CodeIcon,
  BugIcon,
  BranchIcon,
  MergeIcon,
  DatabaseIcon,
} from "./components.js";

// Icon registry - maps icon names to their components
export const iconPaths = {
  "angles-left": <AnglesLeftIcon />,
  "angles-right": <AnglesRightIcon />,
  "angles-up": <AnglesUpIcon />,
  "angles-down": <AnglesDownIcon />,
  "arrow-right": <ArrowRightIcon />,
  "arrow-left": <ArrowLeftIcon />,
  "arrow-up": <ArrowUpIcon />,
  "arrow-down": <ArrowDownIcon />,
  "arrow-up-right": <ArrowUpRightIcon />,
  "arrow-up-left": <ArrowUpLeftIcon />,
  "arrow-down-right": <ArrowDownRightIcon />,
  "arrow-down-left": <ArrowDownLeftIcon />,
  bars: <BarsIcon />,
  "shopping-bag": <ShoppingBagIcon />,
  wallet: <WalletIcon />,
  receipt: <ReceiptIcon />,
  bookmark: <BookmarkIcon />,
  "caret-left": <CaretLeftIcon />,
  "caret-right": <CaretRightIcon />,
  "caret-up": <CaretUpIcon />,
  "caret-down": <CaretDownIcon />,
  calendar: <CalendarIcon />,
  "calendar-plus": <CalendarPlusIcon />,
  "calendar-minus": <CalendarMinusIcon />,
  "calendar-check": <CalendarCheckIcon />,
  "calendar-range": <CalendarRangeIcon />,
  "chevron-left": <ChevronLeftIcon />,
  "chevron-right": <ChevronRightIcon />,
  "chevron-up": <ChevronUpIcon />,
  "chevron-down": <ChevronDownIcon />,
  check: <CheckIcon />,
  circle: <CircleIcon />,
  "circle-check": <CircleCheckIcon />,
  "circle-exclamation": <CircleExclamationIcon />,
  "circle-info": <CircleInfoIcon />,
  "circle-minus": <CircleMinusIcon />,
  "circle-notch": <CircleNotchIcon />,
  "circle-plus": <CirclePlusIcon />,
  "circle-close": <CloseCircleIcon />,
  "x-circle": <CloseCircleIcon />,
  "check-circle": <CircleCheckIcon />,
  info: <InfoIcon />,
  question: <QuestionIcon />,
  close: <CloseIcon />,
  copy: <CopyIcon />,
  clipboard: <ClipboardIcon />,
  "clipboard-list": <ClipboardListIcon />,
  "clipboard-check": <ClipboardCheckIcon />,
  "clipboard-plus": <ClipboardPlusIcon />,
  eye: <EyeIcon />,
  "eye-off": <EyeOffIcon />,
  "double-arrow-horizontal": <DoubleArrowHorizontalIcon />,
  "double-arrow-vertical": <DoubleArrowVerticalIcon />,
  download: <DownloadIcon />,
  edit: <EditIcon />,
  "ellipsis-vertical": <EllipsisVerticalIcon />,
  ellipsis: <EllipsisIcon />,
  "external-link": <ExternalLinkIcon />,
  "log-in": <LogInIcon />,
  "log-out": <LogOutIcon />,
  inbox: <InboxIcon />,
  send: <SendIcon />,
  reply: <ReplyIcon />,
  forward: <ForwardIcon />,
  hashtag: <HashtagIcon />,
  cut: <CutIcon />,
  paste: <PasteIcon />,
  bold: <BoldIcon />,
  italic: <ItalicIcon />,
  underline: <UnderlineIcon />,
  "align-left": <AlignLeftIcon />,
  "align-center": <AlignCenterIcon />,
  "align-right": <AlignRightIcon />,
  "align-justify": <AlignJustifyIcon />,
  grid: <GridIcon />,
  "fast-forward": <FastForwardIcon />,
  bell: <BellIcon />,
  "bell-off": <BellOffIcon />,
  chat: <ChatIcon />,
  "chat-dots": <ChatDotsIcon />,
  flag: <FlagIcon />,
  heart: <HeartIcon />,
  gift: <GiftIcon />,
  "alarm-clock": <AlarmClockIcon />,
  file: <FileIcon />,
  "file-text": <FileTextIcon />,
  "file-image": <FileImageIcon />,
  "file-video": <FileVideoIcon />,
  "file-code": <FileCodeIcon />,
  filter: <FilterIcon />,
  folder: <FolderIcon />,
  "folder-open": <FolderOpenIcon />,
  "folder-plus": <FolderPlusIcon />,
  "folder-minus": <FolderMinusIcon />,
  "map-pin": <MapPinIcon />,
  map: <MapIcon />,
  route: <RouteIcon />,
  "compass-north": <CompassNorthIcon />,
  compass: <CompassIcon />,
  list: <ListIcon />,
  "circle-question": <CircleQuestionIcon />,
  paperclip: <PaperclipIcon />,
  home: <HomeIcon />,
  key: <KeyIcon />,
  globe: <GlobeIcon />,
  link: <LinkIcon />,
  unlink: <UnlinkIcon />,
  lock: <LockIcon />,
  mail: <MailIcon />,
  "mail-open": <MailOpenIcon />,
  "life-buoy": <LifeBuoyIcon />,
  "credit-card": <CreditCardIcon />,
  minus: <MinusIcon />,
  moon: <MoonIcon />,
  clock: <ClockIcon />,
  "location-pin": <LocationPinIcon />,
  pause: <PauseIcon />,
  play: <PlayIcon />,
  phone: <PhoneIcon />,
  "phone-off": <PhoneOffIcon />,
  camera: <CameraIcon />,
  video: <VideoIcon />,
  mic: <MicIcon />,
  "mic-off": <MicOffIcon />,
  headphones: <HeadphonesIcon />,
  monitor: <MonitorIcon />,
  laptop: <LaptopIcon />,
  mobile: <MobileIcon />,
  shuffle: <ShuffleIcon />,
  repeat: <RepeatIcon />,
  "repeat-1": <RepeatOneIcon />,
  "skip-next": <SkipNextIcon />,
  "skip-previous": <SkipPreviousIcon />,
  record: <RecordIcon />,
  "volume-down": <VolumeDownIcon />,
  plus: <PlusIcon />,
  print: <PrintIcon />,
  rectangle: <RectangleIcon />,
  square: <SquareIcon />,
  clouds: <CloudsIcon />,
  cloud: <CloudIcon />,
  "upload-cloud": <UploadCloudIcon />,
  "download-cloud": <DownloadCloudIcon />,
  "battery-empty": <BatteryEmptyIcon />,
  "battery-half": <BatteryHalfIcon />,
  "battery-full": <BatteryFullIcon />,
  wifi: <WifiIcon />,
  signal: <SignalIcon />,
  "cloud-sun": <CloudSunIcon />,
  "cloud-rain": <CloudRainIcon />,
  umbrella: <UmbrellaIcon />,
  thermometer: <ThermometerIcon />,
  refresh: <RefreshIcon />,
  "sort-ascending": <SortAscendingIcon />,
  "sort-descending": <SortDescendingIcon />,
  "shopping-cart": <ShoppingCartIcon />,
  "rotate-left": <RotateLeftIcon />,
  "rotate-right": <RotateRightIcon />,
  rewind: <RewindIcon />,
  save: <SaveIcon />,
  search: <SearchIcon />,
  settings: <SettingsIcon />,
  share: <ShareIcon />,
  tag: <TagIcon />,
  "shield-check": <ShieldCheckIcon />,
  "shield-exclamation": <ShieldExclamationIcon />,
  "shield-lock": <ShieldLockIcon />,
  star: <StarIcon />,
  sun: <SunIcon />,
  stop: <StopIcon />,
  stopwatch: <StopwatchIcon />,
  "zoom-in": <ZoomInIcon />,
  "zoom-out": <ZoomOutIcon />,
  "toggle-off": <ToggleOffIcon />,
  "toggle-on": <ToggleOnIcon />,
  trash: <TrashIcon />,
  unlock: <UnlockIcon />,
  upload: <UploadIcon />,
  user: <UserIcon />,
  "user-check": <UserCheckIcon />,
  "user-edit": <UserEditIcon />,
  "user-settings": <UserSettingsIcon />,
  users: <UsersIcon />,
  pin: <PinIcon />,
  wind: <WindIcon />,
  "cloud-snow": <CloudSnowIcon />,
  "cloud-storm": <CloudStormIcon />,
  "thermometer-plus": <ThermometerPlusIcon />,
  "thermometer-minus": <ThermometerMinusIcon />,
  coupon: <CouponIcon />,
  cube: <CubeIcon />,
  truck: <TruckIcon />,
  "wallet-card": <WalletCardIcon />,
  "user-minus": <UserMinusIcon />,
  "user-plus": <UserPlusIcon />,
  hourglass: <HourglassIcon />,
  "hourglass-half": <HourglassHalfIcon />,
  "hourglass-full": <HourglassFullIcon />,
  "volume-off": <VolumeOffIcon />,
  "volume-up": <VolumeUpIcon />,
  "warning-diamond": <WarningDiamondIcon />,
  "warning-triangle": <WarningTriangleIcon />,
  triangle: <TriangleIcon />,
  "chart-line": <ChartLineIcon />,
  "chart-bar": <ChartBarIcon />,
  "pie-chart": <PieChartIcon />,
  sliders: <SlidersIcon />,
  terminal: <TerminalIcon />,
  code: <CodeIcon />,
  bug: <BugIcon />,
  branch: <BranchIcon />,
  merge: <MergeIcon />,
  database: <DatabaseIcon />,
} as const;

export type IconName = keyof typeof iconPaths;
