import {
  AnglesDownIcon,
  AnglesLeftIcon,
  AnglesRightIcon,
  AnglesUpIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  BarsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleExclamationIcon,
  CircleInfoIcon,
  CircleMinusIcon,
  CircleNotchIcon,
  CirclePlusIcon,
  CloseCircleIcon,
  CloseIcon,
  CopyIcon,
  DoubleArrowHorizontalIcon,
  DoubleArrowVerticalIcon,
  DownloadIcon,
  EditIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  FileIcon,
  FilterIcon,
  FolderIcon,
  HomeIcon,
  KeyIcon,
  LinkIcon,
  LockIcon,
  MinusIcon,
  MoonIcon,
  PlusIcon,
  PrintIcon,
  RefreshIcon,
  RotateLeftIcon,
  RotateRightIcon,
  SaveIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  StarIcon,
  SunIcon,
  ToggleOffIcon,
  ToggleOnIcon,
  TrashIcon,
  UnlockIcon,
  UploadIcon,
  UserIcon,
} from "./components.js";

// Icon registry - maps icon names to their components
export const iconPaths = {
  "angles-left": <AnglesLeftIcon />,
  "angles-right": <AnglesRightIcon />,
  "angles-up": <AnglesUpIcon />,
  "angles-down": <AnglesDownIcon />,
  "arrow-right": <ArrowRightIcon />,
  "arrow-left": <ArrowLeftIcon />,
  "arrow-up": <ArrowUpIcon />,
  "arrow-down": <ArrowDownIcon />,
  "arrow-up-right": <ArrowUpRightIcon />,
  "arrow-up-left": <ArrowUpLeftIcon />,
  "arrow-down-right": <ArrowDownRightIcon />,
  "arrow-down-left": <ArrowDownLeftIcon />,
  bars: <BarsIcon />,
  "caret-left": <CaretLeftIcon />,
  "caret-right": <CaretRightIcon />,
  "caret-up": <CaretUpIcon />,
  "caret-down": <CaretDownIcon />,
  "chevron-left": <ChevronLeftIcon />,
  "chevron-right": <ChevronRightIcon />,
  "chevron-up": <ChevronUpIcon />,
  "chevron-down": <ChevronDownIcon />,
  "circle-check": <CircleCheckIcon />,
  "circle-exclamation": <CircleExclamationIcon />,
  "circle-info": <CircleInfoIcon />,
  "circle-minus": <CircleMinusIcon />,
  "circle-notch": <CircleNotchIcon />,
  "circle-plus": <CirclePlusIcon />,
  "circle-close": <CloseCircleIcon />,
  close: <CloseIcon />,
  copy: <CopyIcon />,
  "double-arrow-horizontal": <DoubleArrowHorizontalIcon />,
  "double-arrow-vertical": <DoubleArrowVerticalIcon />,
  download: <DownloadIcon />,
  edit: <EditIcon />,
  "ellipsis-vertical": <EllipsisVerticalIcon />,
  ellipsis: <EllipsisIcon />,
  "external-link": <ExternalLinkIcon />,
  file: <FileIcon />,
  filter: <FilterIcon />,
  folder: <FolderIcon />,
  home: <HomeIcon />,
  key: <KeyIcon />,
  link: <LinkIcon />,
  lock: <LockIcon />,
  minus: <MinusIcon />,
  moon: <MoonIcon />,
  plus: <PlusIcon />,
  print: <PrintIcon />,
  refresh: <RefreshIcon />,
  "rotate-left": <RotateLeftIcon />,
  "rotate-right": <RotateRightIcon />,
  save: <SaveIcon />,
  search: <SearchIcon />,
  settings: <SettingsIcon />,
  share: <ShareIcon />,
  star: <StarIcon />,
  sun: <SunIcon />,
  "toggle-off": <ToggleOffIcon />,
  "toggle-on": <ToggleOnIcon />,
  trash: <TrashIcon />,
  unlock: <UnlockIcon />,
  upload: <UploadIcon />,
  user: <UserIcon />,
} as const;

export type IconName = keyof typeof iconPaths;
